library(data.table)
library(ggplot2)
data=data.frame(fread('data_500k.tsv.gz',header=T),stringsAsFactors=F)
data$VCF=basename(gsub('.vcf','',data$VCF))
data=data[data$gene=='HTT',]
age_at_recruitment=fread('500K_age_at_recruitment.txt',header=T)
data=merge(data,age_at_recruitment,by.x = 'VCF',by.y = 'eid')

data$CAP_at_recruitment=(data$p21022_Age_at_recruitment*(data$A2-30))/6.49
data$age_when_cap_was_90=round((90*6.49)/(data$A2-30),0)


data=data[!is.na(data$CAP_at_recruitment),]
data=data[,!(colnames(data)%in%c('p21022_Age_at_recruitment'))]
meta_data=data.frame(fread('HTT_project_all_features_meta_file_extra_cols.tsv.gz',sep='\t',header=T),stringsAsFactors=F)
meta_data=meta_data[,!grepl(pattern = '^pNA_Date',colnames(meta_data))]
idx=(colnames(meta_data)%in%colnames(data))
idx[1]=FALSE
meta_data=meta_data[,!idx]
data=merge(data,meta_data,by.x='VCF',by.y='eid')
data$year_when_cap_was_90=data$p34_Year_of_birth+data$age_when_cap_was_90
data$Diagnosed_Huntingtons=NA
data$Diagnosed_Huntingtons[!is.na(data$p131012_Date_G10_first_reported_huntingtons_disease)]='Diagnosed with Huntingtons'
data$Diagnosed_Huntingtons[is.na(data$p131012_Date_G10_first_reported_huntingtons_disease)]='Not Diagnosed with Huntingtons'


self_reported_cols=colnames(data)[grep(pattern='p20002_i',colnames(data))]
self_reported_col_dates=colnames(data)[grep(pattern='Interpolated',colnames(data))]

# self_reported_cols=self_reported_cols[-grep(pattern='cancer|Array|Plasma|death',self_reported_cols)]


convert_single_column_to_event=function(data,cols,date_cols,value_to_detect,new_col_name){
  data=cbind(data,substr(as.character(data[,date_cols]),1,4))
  colnames(data)[ncol(data)]=new_col_name
  data[which(data[,cols]!=value_to_detect),new_col_name]=NA
  
  return(data)
}

convert_self_column_to_event=function(data,cols,date_cols,value_to_detect,new_col_name){
  found_occurences <- apply(data, 1, function(row) {
    values <- as.numeric(row[cols])
    # Normalize dates to year only
    dates <- row[date_cols]
    years <- as.numeric(substr(as.character(dates), 1, 4))  # grab first 4 chars as year
    idx <- which(values == value_to_detect)
    if (length(idx) == 0) {
      return(NA)
    } else if (length(idx) == 1) {
      return(years[idx])
    } else {
      return(max(years[idx], na.rm = TRUE))
    }
  })
  
  # print(found_occurences)
  found_occurences=as.numeric(found_occurences)
  found_occurences[is.infinite(found_occurences)]=NA
  data=cbind(data,found_occurences)
  print(sum(is.na(found_occurences)))
  colnames(data)[ncol(data)]=new_col_name
  # data[!is.na(found_occurences),new_col_name]=paste0(data[!is.na(found_occurences),new_col_name],'-NA-NA')
  return(data)
}

self_reported_cols_out=c()
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1698,'fracture_jaw')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1703,'fracture_clavicle_or_collar_bone')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1704,'fracture_shoulder_or_scapula')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1284,'chronic_or_degenerative_neurological_problem')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1312,'depression')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1313,'anxiety_or_panic_attacks')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1098,'stroke')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1554,'brain_haemorrhage')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1287,'multiple_sclerosis')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1489,'other_neurological_problem')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_self_column_to_event(data,self_reported_cols,self_reported_col_dates,1348,'osteoporosis')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28735_Feeling_anxious._nervous_or_on_edge_over_the_last_2_weeks'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Feeling_anxious._nervous_or_on_edge_over_the_last_2_weeks')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28738_Feeling_down._depressed_or_hopeless_over_the_last_2_weeks'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Feeling_down._depressed_or_hopeless_over_the_last_2_weeks')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28739_Difficulty_with_standing_for_long_periods'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Difficulty_with_standing_for_long_periods')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28740_Difficulty_with_taking_care_of_household_responsibilities'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Difficulty_with_taking_care_of_household_responsibilities')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28741_Difficulty_learning_a_new_task'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Difficulty_learning_a_new_task')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28744_Difficulty_with_concentrating_on_doing_something_for_ten_minutes'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Difficulty_with_concentrating_on_doing_something_for_ten_minutes')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28745_Difficulty_with_walking_a_long_distance'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Difficulty_with_walking_a_long_distance')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28746_Difficulty_with_washing_whole_body'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Difficulty_with_washing_whole_body')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p28751_Difficulty_with_doing_your_day.to.day_work'),c('p28755_When_Health_and_Well.being_Questionnaire_completed'),1,'Difficulty_with_doing_your_day.to.day_work')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p29150_Mobility_problems_today'),c('p29206_When_online_General_health_questionnaire_completed'),1,'Mobility_problems_today')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,c('p29152_Problems_doing_usual_activities'),c('p29206_When_online_General_health_questionnaire_completed'),1,'Problems_doing_usual_activities')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])

data=convert_single_column_to_event(data,c('p29152_Problems_doing_usual_activities'),c('p29206_When_online_General_health_questionnaire_completed'),1,'Problems_doing_usual_activities')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])


data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C160','Date_Death_caused_by_Malignant_neoplasm_Cardia')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C180','Date_Death_caused_by_Malignant_neoplasm_Caecum')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C189','Date_Death_caused_by_Malignant_neoplasm_Colon_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C19','Date_Death_caused_by_Malignant_neoplasm_of_rectosigmoid_junction')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C259','Date_Death_caused_by_Malignant_neoplasm_Pancreas_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C260','Date_Death_caused_by_Malignant_neoplasm_Intestinal_tractpart_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C269','Date_Death_caused_by_Malignant_neoplasm_Ill-defined_sites_within_the_digestive_system')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C349','Date_Death_caused_by_Malignant_neoplasm_Bronchus_or_lung_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C439','Date_Death_caused_by_Malignant_neoplasm_Malignant_melanoma_of_skin_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C449','Date_Death_caused_by_Malignant_neoplasm_Malignant_neoplasm_of_skin_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C56','Date_Death_caused_by_Malignant_neoplasm_of_ovary')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C61','Date_Death_caused_by_Malignant_neoplasm_of_prostate')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C66','Date_Death_caused_by_Malignant_neoplasm_of_ureter')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C679','Date_Death_caused_by_Malignant_neoplasm_Bladder_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C719','Date_Death_caused_by_Malignant_neoplasm_Brain_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C800','Date_Death_caused_by_Malignant_neoplasmprimary_site_unknownso_stated')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C809','Date_Death_caused_by_Malignant_neoplasmprimary_site_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C80','Date_Death_caused_by_Malignant_neoplasm_without_specification_of_site')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','C97','Date_Death_caused_by_Malignant_neoplasms_of_independent_primary_multiple_sites')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','D180','Date_Death_caused_by_Haemangioma_any_site')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','D329','Date_Death_caused_by_Benign_neoplasm_Meninges_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','E86','Date_Death_caused_by_Volume_depletion')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','F019','Date_Death_caused_by_Vascular_dementia_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','F03','Date_Death_caused_by_Unspecified_dementia')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','G10','Date_Death_caused_by_Huntington_disease')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','G122','Date_Death_caused_by_Motor_neuron_disease')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','G20','Date_Death_caused_by_Parkinson_disease')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','G301','Date_Death_caused_by_Alzheimer_disease_with_late_onset')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','G309','Date_Death_caused_by_Alzheimer_disease_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','G318','Date_Death_caused_by_Other_specified_degenerative_diseases_of_nervous_system')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I219','Date_Death_caused_by_Acute_myocardial_infarctionunspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I259','Date_Death_caused_by_Chronic_ischaemic_heart_disease_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I269','Date_Death_caused_by_Pulmonary_embolism_without_mention_of_acute_cor_pulmonale')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I509','Date_Death_caused_by_Heart_failure_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I517','Date_Death_caused_by_Cardiomegaly')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I609','Date_Death_caused_by_Subarachnoid_haemorrhage_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I64','Date_Death_caused_by_Strokenot_specified_as_haemorrhage_or_infarction')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I679','Date_Death_caused_by_Cerebrovascular_disease_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','I739','Date_Death_caused_by_Peripheral_vascular_disease_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','J180','Date_Death_caused_by_Bronchopneumonia_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','J189','Date_Death_caused_by_Pneumonia_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','J440','Date_Death_caused_by_Chronic_obstructive_pulmonary_disease_with_acute_lower_respiratory_infection')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','J47','Date_Death_caused_by_Bronchiectasis')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','K566','Date_Death_caused_by_Other_and_unspecified_intestinal_obstruction')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','K650','Date_Death_caused_by_Acute_peritonitis')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','K746','Date_Death_caused_by_Other_and_unspecified_cirrhosis_of_liver')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','M359','Date_Death_caused_by_Systemic_involvement_of_connective_tissue_unspecified')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','R99','Date_Death_caused_by_Other_ill-defined_and_unspecified_causes_of_mortality')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','U071','Date_Death_caused_by_Emergency_use_of_U071')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
data=convert_single_column_to_event(data,'p40001_i0_Underlying_primary_cause_of_death._ICD10_._Instance_0','p40000_i0_Date_of_death_._Instance_0','Y34','Date_Death_caused_by_Other_specified_events_undetermined_intent')
self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])

mental_heath_cols=colnames(data)[grep(pattern='p19',colnames(data))]
for(m in mental_heath_cols){
  data=convert_single_column_to_event(data,m,'p53_i0',1,paste0('Date_first_reported_',gsub('_._Instance_0','',gsub('p19\\d+_i0','',m))))
  self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
}

# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C160','Date_Death_caused_by_Malignant_neoplasm_Cardia')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C180','Date_Death_caused_by_Malignant_neoplasm_Caecum')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C189','Date_Death_caused_by_Malignant_neoplasm_Colon_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C19','Date_Death_caused_by_Malignant_neoplasm_of_rectosigmoid_junction')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C259','Date_Death_caused_by_Malignant_neoplasm_Pancreas_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C260','Date_Death_caused_by_Malignant_neoplasm_Intestinal_tractpart_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C269','Date_Death_caused_by_Malignant_neoplasm_Ill-defined_sites_within_the_digestive_system')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C349','Date_Death_caused_by_Malignant_neoplasm_Bronchus_or_lung_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C439','Date_Death_caused_by_Malignant_neoplasm_Malignant_melanoma_of_skin_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C449','Date_Death_caused_by_Malignant_neoplasm_Malignant_neoplasm_of_skin_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C56','Date_Death_caused_by_Malignant_neoplasm_of_ovary')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C61','Date_Death_caused_by_Malignant_neoplasm_of_prostate')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C66','Date_Death_caused_by_Malignant_neoplasm_of_ureter')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C679','Date_Death_caused_by_Malignant_neoplasm_Bladder_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C719','Date_Death_caused_by_Malignant_neoplasm_Brain_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C800','Date_Death_caused_by_Malignant_neoplasmprimary_site_unknownso_stated')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C809','Date_Death_caused_by_Malignant_neoplasmprimary_site_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C80','Date_Death_caused_by_Malignant_neoplasm_without_specification_of_site')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','C97','Date_Death_caused_by_Malignant_neoplasms_of_independent_primary_multiple_sites')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','D180','Date_Death_caused_by_Haemangioma_any_site')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','D329','Date_Death_caused_by_Benign_neoplasm_Meninges_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','E86','Date_Death_caused_by_Volume_depletion')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','F019','Date_Death_caused_by_Vascular_dementia_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','F03','Date_Death_caused_by_Unspecified_dementia')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','G10','Date_Death_caused_by_Huntington_disease')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','G122','Date_Death_caused_by_Motor_neuron_disease')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','G20','Date_Death_caused_by_Parkinson_disease')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','G301','Date_Death_caused_by_Alzheimer_disease_with_late_onset')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','G309','Date_Death_caused_by_Alzheimer_disease_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','G318','Date_Death_caused_by_Other_specified_degenerative_diseases_of_nervous_system')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I219','Date_Death_caused_by_Acute_myocardial_infarctionunspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I259','Date_Death_caused_by_Chronic_ischaemic_heart_disease_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I269','Date_Death_caused_by_Pulmonary_embolism_without_mention_of_acute_cor_pulmonale')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I509','Date_Death_caused_by_Heart_failure_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I517','Date_Death_caused_by_Cardiomegaly')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I609','Date_Death_caused_by_Subarachnoid_haemorrhage_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I64','Date_Death_caused_by_Strokenot_specified_as_haemorrhage_or_infarction')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I679','Date_Death_caused_by_Cerebrovascular_disease_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','I739','Date_Death_caused_by_Peripheral_vascular_disease_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','J180','Date_Death_caused_by_Bronchopneumonia_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','J189','Date_Death_caused_by_Pneumonia_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','J440','Date_Death_caused_by_Chronic_obstructive_pulmonary_disease_with_acute_lower_respiratory_infection')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','J47','Date_Death_caused_by_Bronchiectasis')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','K566','Date_Death_caused_by_Other_and_unspecified_intestinal_obstruction')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','K650','Date_Death_caused_by_Acute_peritonitis')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','K746','Date_Death_caused_by_Other_and_unspecified_cirrhosis_of_liver')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','M359','Date_Death_caused_by_Systemic_involvement_of_connective_tissue_unspecified')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','R99','Date_Death_caused_by_Other_ill-defined_and_unspecified_causes_of_mortality')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','U071','Date_Death_caused_by_Emergency_use_of_U071')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])
# data=convert_single_column_to_event(data,'p40001_i1_Underlying_primary_cause_of_death._ICD10_._Instance_1','p40000_i1_Date_of_death_._Instance_1','Y34','Date_Death_caused_by_Other_specified_events_undetermined_intent')
# self_reported_cols_out=c(self_reported_cols_out,colnames(data)[ncol(data)])

data_self_reported=data

data_main=cbind(data_main,data_cogs[,2:ncol(data_cogs)],data_self_reported[,self_reported_cols_out])
write.table(data_main,'HTT_all_columns_death_dates_included_mental_health.tsv',sep='\t',row.names=F,quote=F)

