#!/bin/bash
# compute_pcs 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    echo "Value of ld_params: '$ld_params'"
    echo "chromosomes: '$chroms'" 
    chmod +x /usr/bin/*
    mkdir mount_here
    dxfuse mount_here WGS\ 500k\ release

    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    # The following line(s) use the dx command-line tool to upload your file
    # outputs after you have created them on the local file system.  It assumes
    # that you have used the output field name for the filename for each output,
    # but you can change that behavior to suit your needs.  Run "dx upload -h"
    # to see more options to set metadata.
    # MAF filter + LD pruning

    ln -s "mount_here/WGS 500k release/Bulk/Genotype Results/Genotype calls/" g

    plink --bfile "g/ukb22418_c1_b0_v2" \
      --merge-list "mount_here/WGS 500k release/cc_analysis/merge_list_symlink.txt" \
      --make-bed \
      --chr $chroms \
      --out ukb_merged
# echo "ukb merged_missing"
# grep -f "mount_here/WGS 500k release/cc_analysis/missed_samples" ukb_merged.fam|wc -l
    # Select European and exclude related individuls

    #784256 variants and 8323 people pass filters and QC.
    # Apply minor allele frequency filter
    plink --bfile ukb_merged \
        --maf 0.05 \
        --make-bed \
        --out ukb_maf
# echo "ukb merged_maf"
# grep -f "mount_here/WGS 500k release/cc_analysis/missed_samples" ukb_maf.fam|wc -l
    # undertake iterative missingness with --geno and --mind
    /usr/bin/iterative_missingness.sh $iterative_missingness_params

# echo "ukb cleaned missing"
# grep -f "mount_here/WGS 500k release/cc_analysis/missed_samples2" ukb_cleaned.fam  > missed.txt
# wc -l missed.txt
    plink --bfile ukb_maf_sample97.SNP97 \
        --remove "mount_here/WGS 500k release/cc_analysis/ukbb_non_europeans" \
        --make-bed \
        --out ukb_europeans

# echo "ukb euro missing"
# grep -f "mount_here/WGS 500k release/cc_analysis/missed_samples" ukb_europeans.fam|wc -l

    plink --bfile ukb_europeans \
        --remove "mount_here/WGS 500k release/cc_analysis/related_imaging_toremove_4thSep2025.txt" \
        --make-bed \
        --out ukb_europeans_norelated

# echo "ukb europeans norelated"
# grep -f "mount_here/WGS 500k release/cc_analysis/missed_samples" ukb_europeans_norelated.fam|wc -l
    plink --bfile ukb_europeans_norelated \
        --remove "mount_here/WGS 500k release/cc_analysis/problematic_sex.txt" \
        --make-bed \
        --out ukb_europeans_norelated_nosexmismatch
    # prune dataset to produce between 50,000 and 100,00 SNPs 
    plink --bfile ukb_europeans_norelated_nosexmismatch --indep-pairwise "$ld_params" --make-bed --out ukb_europeans_norelated_nosexmismatch.LD_one
echo "ukb_europeans_norelated_nosexmismatch.LD_one"
# grep -f "mount_here/WGS 500k release/cc_analysis/missed_samples" ukb_europeans_norelated_nosexmismatch.LD_one.fam|wc -l
    # remove pruned SNPs
    plink --bfile ukb_europeans_norelated_nosexmismatch --extract ukb_europeans_norelated_nosexmismatch.LD_one.prune.in --make-bed --out ukb_europeans_norelated_nosexmismatch.LD_two
echo "ukb_europeans_norelat÷ed_nosexmismatch"
# grep -f "mount_here/WGS 500k release/cc_analysis/missed_samples" ukb_europeans_norelated_nosexmismatch.LD_two.fam|wc -l
    awk -f "mount_here/WGS 500k release/cc_analysis/highLDregions4bim_b37.awk"  ukb_europeans_norelated_nosexmismatch.LD_two.bim > highLDexcludes

    awk '($1 < 1) || ($1 > 22) {print $2}' ukb_europeans_norelated_nosexmismatch.LD_two.bim > autosomeexcludes

    cat highLDexcludes autosomeexcludes > highLD_and_autosomal_excludes

    # Remove the High LD excludes
    # 50141 variants and 604 people pass filters and QC.
    plink --bfile ukb_europeans_norelated_nosexmismatch.LD_two \
        --exclude highLD_and_autosomal_excludes \
        --make-bed \
        --out ukb_europeans_norelated_nosexmismatch.LD_three
# echo "ukb_europeans_norelated_nosexmismatch.LD_three missing"
# grep -f "mount_here/WGS 500k release/cc_analysis/missed_samples" ukb_europeans_norelated_nosexmismatch.LD_three.fam|wc -l

    # do PCA
    # plink --bfile ukb_eur_norel.LD_three \
    #         --pca 40 \
    #         --out ukb_pruned_pca
    mkdir output_for_pca
    # mv ukb_pruned.prune.in output_for_pca/
    mv *.fam output_for_pca/
    # mv ukb_europeans.* output_for_pca/
    mv ukb_europeans_norelated_nosexmismatch.LD_three* output_for_pca/

    # mv ukb_pruned_pca.log output_for_pca/

    tar -czvf "$output_prefix".tar.gz output_for_pca/

    PC_data=$(dx upload "$output_prefix".tar.gz --brief)
    dx-jobutil-add-output PC_data "$PC_data" --class=file
    # OR: PCA on all Europeans (practical approach)
    # plink --bfile ukb_europeans \
    #     --extract ukb_pruned.prune.in \
    #     --pca 40 \
    #     --out ukb_pca_final

}
