#!/bin/bash
# ukbb_repeat_crawler 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    # The following line(s) use the dx command-line tool to upload your file
    # outputs after you have created them on the local file system.  It assumes
    # that you have used the output field name for the filename for each output,
    # but you can change that behavior to suit your needs.  Run "dx upload -h"
    # to see more options to set metadata.
    mkdir mount_here
    if [ $mount_project = "500k" ]
    then
        dxfuse mount_here WGS\ 500k\ release
    else
        dxfuse mount_here "$mount_project"
    fi
    ls mount_here
    ls mount_here/*"$folder"/*bam > test_bams
    python3 /usr/bin/RC_latest.py --json mount_here/*$json --span ${span1} --count ${count1} --bam_files test_bams --output "$output_name1" --vcf_informed True --gene $gene --vcf_motif $vcf_motif
    cat $output_name1
    if [ ${output_name2} != "null" ]
    then
    python3 /usr/bin/RC_latest.py --json mount_here/*$json --span ${span2} --count ${count2} --bam_files test_bams --output "${output_name2}" --gene $gene
    fi
    echo "when"
    output1=$(dx upload "$output_name1" --brief --path "output_dir/RC/${output_name1}" -p)
    dx-jobutil-add-output output1 "$output1" --class=file
    echo "where"
    if [ ${output_name2} != "null" ]
    then
        output2=$(dx upload "${output_name2}" --brief --path "output_dir/RC/${output_name2}" -p)
        dx-jobutil-add-output output2 "$output2" --class=file
    fi


    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.
}
