#!/bin/bash
# compute_pcs 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    chmod +x /usr/bin/*
    mkdir mount_here
    dx download "WGS 500k release:"$input_tar -o downloaded_tar.tar.gz
    mkdir tar_input
    tar -xzf downloaded_tar.tar.gz -C tar_input
    path=`ls tar_input`
    # PCA on the subset
    plink2 --bfile tar_input/${path}/ukb_europeans_norelated_nosexmismatch.LD_three \
            --threads 96 \
            --memory 700000000000 \
            --pca approx 40 \
            --out ukb_pruned_pca

    mkdir output_for_pca
    mv ukb_pruned_pca* output_for_pca/
    # mv ukb_pruned_pca.log output_for_pca/

    tar -czvf "$output_prefix".tar.gz output_for_pca/

    PC_data=$(dx upload "$output_prefix".tar.gz --brief)
    dx-jobutil-add-output PC_data "$PC_data" --class=file

}
# dx upload /path/to/your/file.txt --destination project-Gkf6xp0JjB5Xjx8PK4pYP0Yp:/cc_analysis/ --brief